### PR TITLE
React storybook

### PR DESCRIPTION
**Pull request by wdoug**
#### What does this PR do?

Adds [React storybook](https://getstorybook.io/) for the development of React components in isolation independent of having to wire up data from the app. In addition to hopefully making writing components easier, this should be helpful for visual reference and testing of a component library. If that weren't enough, we have wired up `storyshots` to automatically create jest snapshots of component 'stories'.

**Example**:

image

### CODE REVIEW

**Comment by fredmon3** [comment]
@wdoug Due to other merges, this branch will have to be updated from master.

**Comment by wdoug** [comment]
Okay can do

**Comment by wdoug** [comment]
Ah, it looks like there are some new lint warnings. I'll look into those tomorrow

**Review by fredmon3 — APPROVED** [review]
:shipit:

**Pull request merged**
