### PR TITLE
Allow musicians to sign up for events

### LINKED ISSUE #60: Musician Sign Up for Event
As a Volunteer, I need to be able to register for (book) an event, so that the Organizer knows I want to perform. Once I register for an event, the following should happen:
- the event should show up as one of my registered events in the calendar
- the system should send a notification (email by default) to the Organizer that I have registered
- the event should show up in the Organizer's list of Registered events
- The Organizer should see me in the Chat page and be able to chat with me
- I should be taken to the Volunteer Calendar view, where I can see the Event as Registered by me

image

### PR DESCRIPTION
**Pull request by wdoug**
This PR closes #60

#### What does this PR do?

Allows musicians to sign up for events, as well as refactors and improves a couple of things in the app, such as how api tokens don't need to be managed in so many places.

### CODE REVIEW

**Comment by fredmon3** [comment]
As a musician, clicking "Sign Up" on an event seems to do nothing.  I do see that the API call however was made.

**Comment by wdoug** [comment]
Yep, it just makes the api call to make the association currently. It'll be a follow up to actually display the users that have signed up for an event.

**Comment by fredmon3** [comment]
Works for me!  :shipit:

**Comment by wdoug** [comment]
Sweet

**Pull request merged**
