### PR TITLE
Redux persist

### PR DESCRIPTION
**Pull request by wdoug**
#### What does this PR do?

Improves refresh handling by: 
- persisting the whole redux app state to localStorage
- validating that the user is still logged in on refresh
- redirects to login for authenticated routes, and returns back to the initial route after logging in

### CODE REVIEW

**Review by dviramontes — APPROVED** [review]
👍

**Review by darrenrichmond — COMMENTED** [review]
@wdoug , when I test this in heroku, I get an error when I create an event: The `Event` instance is not valid. Details: `created` can't be blank (value: undefined).

**Comment by wdoug** [comment]
Ah yes @darrenrichmond that was fixed in another pull request. Let me rebase this off master.

**Comment by wdoug** [comment]
@darrenrichmond I went back and tested that, and with the rebase it looks good.

I am going to go ahead and merge.

**Pull request merged**
